KnowYourJMI/KnowYourJMI/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Index.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('thanks/',views.Thanks.as_view(),name='thanks'),
    path('students/',include('Students.urls', namespace='students')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns+=[path('__debug__/',include(debug_toolbar.urls))]

KnowYourJMI/Students/urls.py
from django.urls import path
from . import views

app_name='students'
urlpatterns=[
    path('',views.StudentListView.as_view(), name='students'),
    path('<int:pk>/',views.StudentDetail.as_view(), name='single'),
]

KnowYourJMI/accounts/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name='accounts'

urlpatterns=[
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.Signup.as_view(),name='signup')
]

KnowYourJMI/Students/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.contrib.auth import get_user_model
# Create your models here.

User=get_user_model()

KnowYourJMI/accounts/models.py
from django.db import models
from django.contrib import auth
# Create your models here.

class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return '@{}'.format(self.username)

KnowYourJMI/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class userCreateForm(UserCreationForm):
    class Meta():
        fields=('username', 'email', 'password1', 'password2')
        model=get_user_model()
        labels={'username':'Name','email':'Email Adress'}

KnowYourJMI/KnowYourJMI/views.py
from django.views import generic

class Index(generic.TemplateView):
    template_name='index.html'

class Thanks(generic.TemplateView):
    template_name='thanks.html'
    

KnowYourJMI/Students/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.views import generic
from django.http import Http404
from django.contrib.auth import get_user_model
from . import models
# Create your views here.

User=get_user_model()
class StudentListView(generic.ListView):
    model=User
    queryset=User.objects.all()
    template_name='Students/students_list.html'
class StudentDetail(generic.DetailView):
    model=models.User
    template_name='Students/students_detail.html'

KnowYourJMI/accounts/views.py
from django.shortcuts import render
from django.views import generic
from . import forms
from django.urls import reverse_lazy
# Create your views here.

class Signup(generic.CreateView):
    form_class=forms.userCreateForm
    success_url=reverse_lazy('accounts:login')
    template_name='accounts/signup.html'

KnowYourJMI/Students/templates/Students/students_base.html
{% extends "base.html" %}
{% block content %}
<div class="row">
  {% block precontent %}{% endblock %}
</div>
<div class="row">
  {% block incontent %}{% endblock %}
</div>
<div class="row">
  {% block postcontent %}{% endblock %}
</div>
{% endblock %}

KnowYourJMI/Students/templates/Students/students_detail.html
{% extends "Students/students_base.html" %}
{% block precontent %}
<div class="container-fluid">
  <h1>{{user.username}}</h1>
</div>
{% endblock %}

KnowYourJMI/Students/templates/Students/students_list.html
{% extends "Students/students_base.html" %}
{% block precontent %}
<div class="container">
  <h1>List of all students:</h1>
</div>
{% endblock %}
{% block incontent %}
<div class="jumbotron">
  <ul class="list-group list-group-horizontal">
  {% for student in user_list %}
  <a href="{% url 'students:single' pk=student.id %}" class="list-group-item list-group-item-action">
    <li class="list-group-item">{{student.username}}</li>
  </a>
  {% endfor %}
  </ul>
</div>
{% endblock %}

KnowYourJMI/Students/templates/Students/stutents_detail.html
{% extends "Students/students_base.html" %}
{% block precontent %}
  <h1>{{Students.user.username}}</h1>
{% endblock %}

KnowYourJMI/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
  <h1>Login</h1>
  <div class="container">
    <form method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-primary" value="Login">
    </form>
  </div>
{% endblock %}

KnowYourJMI/accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<h1>SignUp</h1>
<div class="container">
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary" value="Register">
  </form>
</div>
{% endblock %}

KnowYourJMI/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>KnowYourJMI</title>
    {# js and jQuery #}
    <!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    <link rel='icon' href="https://www.noticebard.com/wp-content/uploads/2017/03/jamia-millia-islamia.jpg">
    {# apni css #}
    <link rel="stylesheet" href="{% static "css/master.css" %}">
    <!-- CSS only -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

{# font #}
<link href="https://fonts.googleapis.com/css2?family=Baloo+Da+2:wght@500&display=swap" rel="stylesheet">

  </head>
  <body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'home' %}">KYJ</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    {% if user.is_authenticated %}
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'students:students' %}">
          Students
        </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'accounts:logout' %}">
          Logout
        </a>
      </li>
    </ul>
    {% else %}
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'students:students' %}">
          Students
        </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'accounts:login' %}">
          Login
        </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'accounts:signup' %}">
            Signup
        </a>
      </li>
    </ul>
    {% endif %}
  </div>
</nav>
  {% block content %}

  {% endblock %}
  <div class="card-footer text-muted">
    <div class="row">
      <div class="col-sm-2">
        <p>follow us on: </p><br>
      </div>
     <div class="col-sm-2">
       <a href="https://www.instagram.com" target="_blank"><img src="https://logonoid.com/images/instagram-logo.png" alt="IG" width="20"></a>
     </div>
     <div class="col-sm-2">
       <a href="https://www.linkedin.com" target="_blank"><img src="https://image.flaticon.com/icons/png/512/124/124011.png" alt="linkedIn" width="20"></a>
     </div>
     <div class="col-sm-2">
       <a href="https://tweeter.com" target="_blank"><img src="https://blog.bitmex.com/wp-content/uploads/2018/10/kisspng-social-media-iphone-organization-logo-twitter-5abe3024502f30.2043853815224136043284.jpg" alt="Tweeter" width="20"></a>
     </div>
   </div>
 </div>
  </body>
</html>

KnowYourJMI/templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron index-heading">
<div class="container">
  <img src="https://upload.wikimedia.org/wikipedia/en/thumb/d/df/Jamia_Millia_Islamia_Logo.svg/222px-Jamia_Millia_Islamia_Logo.svg.png" alt="JMI logo" width="100">
  <h1>Jamia Millia Islamia</h1>
  <h2>Welcome Freshers!!</h2>
</div>
</div>
{% endblock %}

KnowYourJMI/templates/thanks.html
{% extends "base.html" %}
{% block content %}
  <h1><strong>Thanks for your visit!</strong> Hope to meet you soon.</h1>
{% endblock %}